export const MOCK_POSTS = [
  {
    _id: "1",
    title: "Building Scalable APIs with Node.js & Express",
    username: "chakra_dev",
    createdAt: "2026-05-28T10:00:00Z",
    likeCount: 148,
    commentCount: 23,
    tag: "Backend",
    readTime: "6 min",
    image: null,
  },
  {
    _id: "2",
    title: "React Server Components: A Deep Dive",
    username: "frontend_owl",
    createdAt: "2026-05-27T08:00:00Z",
    likeCount: 312,
    commentCount: 47,
    tag: "React",
    readTime: "9 min",
    image: null,
  },
  {
    _id: "3",
    title: "Why TypeScript Still Wins in 2026",
    username: "tserious",
    createdAt: "2026-05-25T14:00:00Z",
    likeCount: 89,
    commentCount: 11,
    tag: "TypeScript",
    readTime: "4 min",
    image: null,
  },
  {
    _id: "4",
    title: "MongoDB Aggregation Pipelines Explained",
    username: "db_sage",
    createdAt: "2026-05-23T09:00:00Z",
    likeCount: 205,
    commentCount: 31,
    tag: "Database",
    readTime: "7 min",
    image: null,
  },
];